version: '3.3'

networks:
  testnet:
    name: testnet
    external: true

services:
  nextcloud-app:
    image: nextcloud:latest
    container_name: nextcloud_app
    restart: #set as unless-stopped, always, or never (don't do never)
    ports:
      - :80 #set a local port (above 2000 is recommended cuz below that gets used more often)
    volumes:
      - :/var/www/html #set a local directory recommended to make a folder in the working directory of this file and a different folder for each service
    environment:
      - MYSQL_PASSWORD= #set a password (none of these ar important as long as the passwords and usernames are all the same)
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER= #set a username
      - MYSQL_HOST=nextcloud-db
    networks:
      - testnet

  nextcloud-db:
    image: mariadb:latest
    container_name: nextcloud_db
    restart: #set as unless-stopped, always, or never (don't do never)
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - :/var/lib/mysql #set a local directory
    environment:
      - MYSQL_ROOT_PASSWORD= #set a password
      - MYSQL_PASSWORD= #set a password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud #set a username
    networks:
      - testnet